#+TITLE:     BASGRA_N User Guide
#+AUTHOR:    MvO
#+OPTIONS:   ^:nil, _:nil
#+ATTR_LATEX: placement=[H]

* Introduction
- BASGRA_N is a new version of the BASGRA model for growth and
  overwintering of grasslands. The new model was developed to allow
  simulation of additional phenomena: (1) the impact of N-supply on
  the plants and their environment, (2) the dynamics of greenhouse
  gases in plants and soil, (3) the dynamics of cell-wall content and
  digestibility of leaves and stems.
- The new model simulates the carbon-, nitrogen- and water-cycles in
  the plant-soil system in some detail. The previous model,
  BASGRA2014, lacked the nitrogen cycle and only simulated
  carbon-processes in the plants, not the soil. So the main processes
  added to the previous model are simulation of C and N in the soil,
  and of N in the plants. The dynamics of cell/wall content and
  digestibility are simulated using simple empirical functions of
  phenological stage.
- We refer to the user guide of BASGRA2014 (downloadable from Van
  Oijen et al. 2015) for a description of all unchanged processes. The
  present user guide focuses on the new parts of the model. We begin
  by giving a summary overview of the changes, and then give more
  details of the new processes. This is followed by a section that
  lists the files that have changed (BASGRA is implemented as a
  collection of multiple FORTRAN- and R-files, only some of which were
  changed to produce BASGRA_N). Then a first evaluation of the new
  model is given and some key references. Finally, in an Appendix,
  details of the exact code changes in modified files are described.
* Summary of model changes compared to BASGRA_2014
** New state variables and processes
- BASGRA2014 had 23 state variables, of which 13 referred to plant
  variables and 10 to environmental variables. BASGRA_N has one extra
  plant state variable (NSH, the amount of nitrogen in aboveground
  plant parts; g N m-2) and seven extra soil state variables
  representing mineral nitrogen plus C and N in three other soil
  pools: litter and two forms of organic matter differing in
  decomposition rate. This brings the total number of state variables
  in BASGRA_N to 31 (14 plant, 17 environment). Nitrogen in roots is
  not simulated as a state variable but as root carbon times a
  constant N-C ratio, and nitrogen in reserves is considered absent.
- The dynamics of the new plant state variable NSH are the net result
  of growth (incorporating N taken up from the soil and from
  remobilisation), senescence and harvesting. The dynamics of the
  seven new soil state variables are simulated in the same way as in
  the forest model BASFOR (Van Oijen et al. 2005). The pool sizes vary
  as a result of external inputs (fertilisation, deposition,
  fixation), decomposition, uptake by plants, and losses to the
  environment (leaching, gaseous emission).
** New inputs
- BASGRA_N requires the same input variables as BASGA2014, plus two
  new ones. The weather variables are the same: daily time series of
  radiation, temperature, precipitation, wind speed and humidity. Also
  retained is the need to supply the time schedule of grass
  cutting. The two new input time series are for fertilisation and for
  atmospheric deposition, both expressed in g N m-2 d-1.
** New outputs
- In principle, every variable simulated by BASGRA_N can be included
  in the list of output variables. But in the archived version of
  BASGRA_N, a limited number of output variables are specified. These
  include the 31 state variables as well as process rates and
  intermediate variables of all three cycles (C, N and water) and of
  cell-wall content and digestibility. New outputs also include crude
  protein content and ash content, both of which are estimated as
  linear functions of shoot nitrogen content.
** New parameters
- The total number of model parameters has increased from 81 in
  BASGRA2014 to 113 in BASGRA_N. The new parameters include initial
  constants for the new state variables, control coefficients for new
  processes, N-C ratios and relative death rates of roots and stubble.
* Assumptions, processes, mechanisms
- We first describe the N-processes in the plants, and then give a
  summary of C- and N-processes in the soil. The soil description will
  be kept short because most of the mechanisms can be found in other
  models, in particular BASFOR (Van Oijen et al. 2005). We conclude by
  describing the processes of change in cell-wall content and
  digestibility.
** Simulation of N in the plants
*** Availability of N, the "N-source"
- At every time step, the availability of N to the plants is
  determined by the amount of soil mineral N (state variable NMIN; g N
  m-2), plus the amount of N that becomes available from within the
  shoots by remobilisation.
- N-remobilisation is calculated by comparing the amount of N actually
  present in the shoots (NSH) to the amount of N that we would have
  seen if N-C ratio followed the same exponential profile in the sward
  as light, starting from the maximum N-C value allowed by the model
  at the top (NCSHMAX). In the model, that "expected" amount of shoot
  N is called NSHK, which can be read as "the amount of N in shoots if
  the profile would follow the light extinction coefficient K". The
  formula for NSHK is the following:
- NSHK = CSH * NCSHMAX * (1-exp(-K*LAI))/(K*LAI),
- where CSH = CLV+CST, i.e. carbon in leaves plus stems. The term
  "CSH*NCSHMAX" is the maximum possible amount of shoot-N (maximum N-C
  ratio at all positions), and the final term is the fraction of that
  maximum that is realised in an exponential profile with coefficient
  K.
- Often NSH > NSHK, and we assume that the excess nitrogen (NSH -
  NSHK) becomes available for growth at a given time constant. That
  process is called remobilisation.
- NMIN is available for plant uptake, but not all of it at the same
  time: the maximum plant uptake rate of soil mineral nitrogen is
  calculated as NMIN divided by a given time constant. Apart from
  plant uptake, NMIN is also depleted by loss to the environment
  (leaching, emission), and it is replenished from decomposition of
  organic material and from external inputs in the form of deposition,
  fertilisation and/or fixation. This makes NMIN into a highly dynamic
  variable that never contains more than a small fraction of total
  soil N, but one that plays a key role in regulating plant processes.
- So in the model, the N-source available for growth is equal to the
  excess of shoot-N plus soil mineral N, both terms divided by their
  own time constant.
*** Requirement for N, the "N-sink"
- In all versions of BASGRA, allocation of carbon to shoot growth
  depends on the balance between C-availability (from photosynthesis
  and reserves) and C-demand by leaves and stems. We refer to the
  shoot demand for C as its "sink strength". In BASGRA_N, a small
  N-source reduces shoot sink strength, but does not affect the sink
  strength of other processes. The effect of a limiting N-source on
  the shoot sink (for growth in terms of carbon) is assumed to be
  proportional to the N-source divided by the product of shoot
  sink and a maximum shoot N-C ratio. The latter product can be viewed
  as the N-sink of the plants. So shoot carbon sink is proportional to
  the source-sink ratio for N. In yet other words, when the N-source
  is too low to support shoot growth at maximum nitrogen
  concentration, shoot growth rate is reduced proportionately. The
  proportionality factor is called 'fNgrowth' in the model.
*** Effects of N-limitation  on other plant processes than growth
- Apart from influencing shoot sink strength and thereby allocation
  patterns, N-limitation does not have an immediate effect on plant
  light-use efficiency because the Rubisco-content and N-C ratio of
  upper leaves (parameter RUBISC, g m-2 leaf; parameter NCSHMAX, g
  g-1) are assumed to be constant. There is, however, an immediate
  effect on tillering: the leaf appearance rate, which provides site
  for tillering, is also proportional to fNgrowth. Note, however, that
  all other plant processes will also, but indirectly, be affected in
  the long-run by any changes in allocation.
*** Dynamics of plant N-C ratios
- The overall N-C ratio of stems and leaves, NCSH, is considered
  variable in BASGRA_N. In contrast, the N-C ratio of roots is assumed
  to be constant, and that of reserves is assumed to be zero. Although
  NCSH is variable, it is not fluctuating strongly, despite the fact
  that three processes affect it. These processes are growth,
  senescence and harvesting. All three processes change NCSH by adding
  or removing tissue that is not at the average N-C ratio. We assume
  that (1) growth adds young material at a ratio higher than average,
  (2) harvesting removes tissue also at higher-than-average N-C ratio,
  while (3) senescence removes tissue at lower than average N-C ratio.
- Calculation of the N-C ratios at which the three processes proceed
  is based on the assumption that nitrogen concentration follows an
  exponential function of LAI, counting from the youngest leaves
  downward. So a very small amount of shoot growth would have the
  maximum N-C ratio (parameter NCSHMAX), and greater amounts of new
  shoot growth would have slightly lower N-C ratios. Likewise, the
  harvested material from a very small cut would have high N-C ratio
  whereas big cuts would have lower N-C ratio because older, lower-N
  tissue would be included in the harvest. The loss of N in senescence
  also adheres to the concept of an exponential aboveground profile of
  N, but the assumption is here that the lowest-N tissue dies first,
  so days with high senescence may have slightly greater losses of N
  per unit tissue than days with only minor senescence. All these
  calculations require us to estimate KN, the "extinction coefficient
  for N" in the sward profile.
*** Derivation of the N-extinction coefficient, KN
- Assuming that nitrogen follows an exponentially decreasing curve in
  the canopy, starting from a given maximum N-C ratio at the top
  (NCSHMAX), we should in principle be able to calculate KN as a
  function of total aboveground leaf area (LAI) and nitrogen
  (NSH). However, as we show now, there is no analytical solution to
  this problem, so we developed a somewhat intricate approximating
  equation for KN.
- As a general observation, we can say that if NSH > NSHK, then KN must
  be less than K (nitrogen "extinguishes" less quickly than light does)
  and if NSH<NSHK then KN > K. More precisely, KN can be solved from
  the following equation, similar to the one for NSHK above but with a
  different exponential coefficient:
- NSH = CSH * NCSHMAX * (1-exp(-KN*LAI))/(KN*LAI).
- Unfortunately that equation cannot be solved analytically for KN,
  because of the exponential term. In other words, even if all terms
  apart from KN itself are known, we cannot directly find the value of
  KN. However, we can find an approximation to KN by replacing the
  exponential term by its third-order Taylor expansion around KN equal
  to zero:
- 1-exp(-KN*LAI) = (approximately) KN*LAI - (KN^2*LAI^2)/2 + (KN^3*LAI^3)/6.
- Plugging that approximation into the equation for NSH gives a
  quadratic equation that can be solved:
- NSH = CSH * NCSHMAX * (1 - KN*LAI/2 + KN^2*LAI^2/6),
- and the solution of this quadratic equation is:
- KN = (approximately) (3/2 ± 3 * sqrt(1/4 -
  (2/3)*(1-NSH/(CSH*NCSHMAX)))) / LAI.
- Note that NSH/(CSH*NCSHMAX) must be larger than 5/8 to ensure that
  the square-root is a real number. The approximation for KN may lead
  to extreme values of KN when KN*LAI becomes large, but we can
  strengthen it by respecting an upper bound (called KNMAX) for KN
  derived from the equation for NSH as follows. Because the term
  (1-exp(-KN*LAI)) < 1, we find that:
- KN < KNMAX = CSH * NCSHMAX / (NSH * LAI)
- We now check the quality of the approximation for KN for two extreme
  values of NSH: NSH = CSH*NCSHMAX and NSH = NSHK. We begin with the
  first case where we have a uniform profile of N with an N-C ratio
  that is everywhere equal to NCSHMAX. In other words, KN should be
  zero. We check this by plugging "NSH=CSH*NCSHMAX" into our
  approximative equation for KN and find that it simplifies to:
- KN_(NSH uniform) = (approximately) (3/2 ± 3 * sqrt(1/4)) / LAI = (3/2 ± 3/2) /
  LAI,
- and this indeed simplifies to KN = 0 provided we choose the
  "minus"-solution of the quadratic equation. From now on we assume
  that the minus-solution is the correct one and turn to the second
  case: NSH = NSHK. In that case we should find - if our approximative
  equation is any good - that KN is about equal to the light
  extinction coefficient K. So we plug the equation given above for
  NSHK into our approximative equation for KN and find:
- KN_(NSH=NSHK) = (approximately) (3/2 - 3 * sqrt(1/4 -
  (2/3)*(1-(1-exp(-K*LAI))/(K*LAI)))) / LAI
- We checked this result in EXCEL for many values of K and LAI. For
  small values of K*LAI, the approximation is excellent. For large
  values of K*LAI the approximation becomes increasingly worse, but
  KN's upper bound (KNMAX = CSH*NCSHMAX/(NSH*LAI)) then comes to the
  rescue: KNMAX becomes increasingly close to the light extinction
  coefficient K. We can see that as follows:
- KN_(NSH=NSHK) < KNMAX_(NSH=NSHK) = CSH*NCSHMAX/(NSHK*LAI) = K /
  (1-exp(-K*LAI)),
- where the denominator of the ratio gets increasingly close to unity
  when K*LAI becomes big.
- So also for this very different case, the approximative equation for
  KN, with upper bound, works well.
*** KN: rule and role
- The previous paragraph showed how we derived an approximative
  equation for KN, and an upper bound for it. Taking everything
  together, we work with the following rule for KN in the model:
- If NSH/(CSH*NCSHMAX) >= 5/8 then KN is assumed equal to the
  negative-branch solution of the approximative quadratic equation or
  to KNMAX, whichever is smaller, and
- If NSH/(CSH*NCSHMAX) < 5/8 then KN is assumed equal to KNMAX.
- The role of KN in the model is to make sure that the effects of
  growth, harvesting and senescence on NSH are calculated
  correctly. These processes increase or decrease shoot biomass, and
  the amount of N that is gained or lost should be consistent with the
  N-profile as measured by KN. We only show how this is calculated for
  senescence, but fairly similar equations apply to the two other
  processes. Daily senescence removes an amount DLAI from the LAI. The
  amount of carbon lost is less than DLAI/LAI because we assume that
  stems do not senesce. And the fraction of nitrogen lost in the same
  process is even less than that because we assume that senescent
  tissue is at the lower end of the exponential profile of N-C ratio
  in the canopy. We calculate the fraction of NSH lost in senescence
  as 1 minus the fraction of N remaining in leaves (stems are
  disregarded), and for that calculation we use the "nitrogen
  extinction coefficient" KN. The fraction of leaf biomass remaining
  (i.e. not senescing) is (LAI-DLAI)/LAI. The fraction of leaf N in
  the corresponding part of the exponential curve is equal to:
- Fraction non-senescing leaf N = (1-exp(-KN*(LAI-DLAI))) / (1-exp(-KN*LAI))
- So our estimate for the fraction of leaf N lost in daily senescence
  is 1 minus that amount. We may need to correct that estimate because
  KN, after all, is only approximated and not exactly known. We ensure
  that the N-C ratio of the senescing leaf tissue is not so low that
  the remaining biomass has more than the maximum permitted N-C ratio,
  NCSHMAX:
- DNSH >= NSH - NCSHMAX * (CSH-DLV),
- where DLV is the carbon loss from the shoot (i.e. dying leaves) in
  senescence. So in the model, we take the loss of shoot N in
  senescence, DNSH, to be the maximum of our profile-based estimate
  and the amount needed to ensure that NCSH <= NCSHMAX.
** Simulation of N in the soil
- The simulation of carbon and nitrogen in the soil follows the scheme
  for carbon devised by Goudriaan (1990), which we extended with
  nitrogen dynamics. We distinguish three general pools in the soil:
  litter ("LITT"), organic matter with a fast turn-over rate ("SOMF"),
  and organic matter with a slow turn-over rate ("SOMS"). Each type of
  soil pool contains both C and N, and their ratios can vary to some
  extent. So there are six state variables called CLITT, CSOMF, CSOMS,
  NLITT, NSOMF, NSOMS. Shoot senescence contributes to LITT, at the
  N-C ratio of the senescing material, and root senescence contributes
  to SOMF at the N-C ratio of the roots which is a
  constant. Furthermore there are continuously operating
  transformations from LITT to SOMF to SOMS, in each case with some of
  the C being lost as CO2 and some of the N being lost to the soil
  mineral pool NMIN.
** Simulation of cell-wall content and digestibility
- Our submodel for cell-wall content and digestibility is intermediate
  in complexity between the models of Gustavsson et al. (1995) and
  that of Bonesmo & Bélanger (2002).
- We added a subroutine 'Digestibility' to plant.f90 that calculates
  cell-wall-content (g g-1 DM) and digestibility (dimensionless) of
  leaves and stems.
- The subroutine calculates cell-wall content of:
  - leaves
  - stems
  - shoot dry matter (DMSH = DMLV + DMST + DMRES)
  - total aboveground dry matter (DM = DMSH + DMSTUB) 
- The subroutine calculates digestibility of:
  - leaves
  - stems
  - cell walls overall
  - shoot dry matter
  - total aboveground dry matter
- The algorithm assumes that all dry matter other than cell walls is
  fully digestible. Digestibility of cell walls decreases linearly
  with phenological state (PHEN). Leaves, stems and stubble have
  different cell-wall fractions but cell-wall digestibility itself
  does not differ among the different plant components. The cell-wall
  contents of both leaves and stems increase linearly with
  phenological state and are generally higher in stems than in
  leaves. Cell-wall content of reserves is zero and of stubble 100%.

* Implementation of BASGRA_N
- BASGRA_N is implemented in the same way as BASGRA2014, in the form
  of eight FORTRAN files that define model structure and
  parameterisation, plus a number of R-files for running the model and
  analysing the results. In this section, we merely name the files
  that were changed, for more details see the Appendix on "Details of
  file changes"
** FORTRAN files
- The eight FORTRAN files (with extension ".f90") are:
  - BASGRA.f90
  - environment.f90
  - parameters_plant.f90
  - parameters_site.f90
  - plant.f90
  - resources.f90
  - set_params.f90
  - soil.f90
- Three of these files (parameters_plant.f90, parameters_site.f90,
  set_params.f90), together with an ASCII-file (parameters.txt), set
  the parameter values of the model.
- The remaining five f90-files form the heart of the model,
  representing the processes. The state equations - which define how
  the state variables are updated every time step - and the output
  variables are defined in 'BASGRA.f90'. The file 'environment.f90' is
  identical to the previous model version and simulates
  meteorology. The file 'resources.f90', which simulates light
  absorption and evapotranspiration, is also essentially unchanged
  apart from minor tidying up of the code. The file 'soil.f90' has
  changed considerably to include representation of the soil C- and
  N-cycles as well as nitrogen deposition and fertilisation. The file
  'plant.f90' has also changed much.
** R-files
- BASGRA_N uses the same suite of R-files as BASGRA2014 does for
  running the model, analysing results and carrying out Bayesian
  calibration of parameter distributions. There are some minor
  changes in some of the files:
  - In the following files, calendars for fertilisation and deposition
    are introduced: 'BC_BASGRA_MCMC.R',
    'BC_BASGRA_MCMC_init_general.R', 'BC_plot_outputs_data.R',
    'initialise_BASGRA_general' and all the 'initialisation_BASGRA...'
    files.
  - 'BC_BASGRA_MCMC_init_general.R' has also been tidied up (unused code
    removed).
  - In 'initialise_BASGRA_general', names and units of new output
    variables are added, and an error in the calculation of 'sumdata'
    was corrected (the column number has been changed from 2 to 4,
    i.e. the column with the data values).
* Evaluation and outlook
- Preliminary tests with this version of BASRA_N suggest that the
  model works well. However, this has to be checked in
  greater detail. Moreover, there are various parts of BASGRA_N that
  may be oversimplifications requiring further model development.
** Needs for further model testing
- The following processes may require closer attention:
  - Dynamics of root-shoot ratio. There may be many data on this
    variable, but we have not checked yet how it responds to N-supply in
    the model.
  - Full N-budgets with all processes of nitrogen import and
    export. Such budgets can be set-up for:
    - the whole soil-plant system,
    - soil,
    - plants,
    - above-ground biomass
** Data needs
- With the introduction of the N-relations in plant and soil, the
  model has become more data hungry. So there are questions about the
  availability of data for:
  - N-concentration ranges in timothy
  - Time series of state variables
  - General patterns of response to N (e.g. root-shoot ratio responses)
  - Impact of fertilisation
  - Impact of mixing with N-fixers (clover)
  - Information on remobilisation of N from senescent material
** Further model structural development
- The following parts of the model may be reconsidered.
*** LUE
- At present, there is no direct effect of the sward N status on
  light-use efficiency (LUE). We may wish to make the LUE dependent on
  fNgrowth or, perhaps more plausibly, the N-C ratio of the shoot,
  NCSH.  We may encounter problems with circularity if we make
  fNgrowth affect other processes, as it is calculated based on the
  /actual/ total carbon growth rate of the plants, not the potential
  rate.
- If we choose to implement an effect of NCSH on LUE, then maybe the
  parameter RUBISC can be removed from the model and, in subroutine
  LUECO2TM, be replaced by a /variable/ RUBISC, calculated as being
  directly proportional to NCSHMAX. Also in that LUE-subroutine, the
  light extinction coefficient K may be replaced by the nitrogen
  extinction coefficient KN although that is not fully consistent with
  the concepts on which the LUE-calculation is based. An alternative
  method would be to calculate LUE as before but modify it then as a
  function of fNgrowth or NCSH/NCSHMAX.
*** The new algorithm for calculating the nitrogen profile (KN)
- At present, KN is estimated by solving a quadratic equation (and
  also recognising an upper bound to KN). Another way of modeling this
  would be to use a loop in which we find iteratively the KN-value
  that gives an estimated NSH value (let's call it "NSH(KN)") within a
  small error from the actual value of NSH in the model. That is
  perhaps not elegant and also computationally demanding. However, we
  can use one single iteration of that idea as follows:
  - Estimate KN as we do now
  - Use that estimated KN to calculate NSH(KN)
  - Compare NSH(KN) to NSH. If NSH(KN) > NSH then we need to adjust
    our estimate of KN, i.e. increase KN somewhat. If NSH(KN) < NSH,
    then we need to decrease KN somewhat.
*** Nitrogen uptake
- At present N-uptake is not a function of root biomass (CRT) or
  rooting depth, based on the assumption that mineral N is very mobile
  in soils and will generally move to roots sufficiently fast (given a
  certain time constant) to meet plant N-demand, irrespective of root
  system size. This assumption needs to be tested.
*** Nitrogen in stems, leaves and stubble
- NCSH is often observed to decrease with increasing biomass. We need
  to check whether the model reproduces that phenomenon. The reduction
  of NCSH may be caused, partly or completely, by an increase in the
  stem fraction of biomass, as stems are known to often have lower N-C
  ratio than leaves. The nitrogen in stems and leaves is currently
  lumped in the variable NSH, so we may want to separate this into NST
  and NLV, both with their own variable N-C ratio. We also need to
  check carefully in such a new model version (and in the current one)
  that the way senescence in terms of nitrogen is calculated is
  consistent with the senescence equations for carbon.
- Another consideration is whether the model assumption of zero N in
  stubble is justified.
*** Nitrogen in roots
- We may want to check whether the nitrogen source-sink calculations
  are considering the roots appropriately. Root growth requires
  nitrogen at a constant N-C ratio. Is this taken into account
  correctly in the calculation of the "plant nitrogen sink strength"?
*** Dynamics of soil mineral nitrogen
- Currently, the model code includes a line that sets NMIN to zero
  whenever the simulations lead to a (possibly very small) negative
  value. This positiveness-constraint is not elegant and only
  introduced because of numerical errors in the solution of the model
  equations. However, we may want to remove the need for this
  artificial approach by reformulating the processes affecting NMIN
  rather than NMIN itself - to ensure that the N-balance in the
  calculations remains closed.
*** Possible simplifications
- The N-C ratio of shoot growth may not need to be calculated as a
  function of KN if we assume that all new growth proceeds at the
  maximum N-C ratio of NCSHMAX.
- The line in the calculation of nitrogen loss associated with
  harvesting, where we ensure that the N-remaining (the unharvested
  material) is not exceeding the maximum N-C ratio, NCSHMAX, may be
  superfluous because the N-C ratio of harvested material should
  always be more than average (i.e. more than NCSH), given that KN
  cannot be less than zero and that tissue is harvested starting from
  the high-N top.
*** New processes
- There may be a use for simulating the uptake of amino acids, rather
  than mineral N, from manure, as scientific interest in the dynamics
  of organic N seems to be increasing.
*** Comparison with other models
- We need to investigate more closely how BASGRA_N compares to other
  grassland models or crop models including nitrogen relations:
- SPACSYS
  - Wu et al. 2007
  - Wu et al. (incl. Bob Rees and Andy Whitmore) 2015
- CATIMO
- STICS
- GECROS (Yin)
* References
- Bonesmo H. & Bélanger G. (2002). Timothy yield and nutritive value by
  the CATIMO model. 2. Digestibility and fiber. Agronomy Journal 94:
  345-350.
- Goudriaan, J (1990). Atmospheric CO2, global carbon fluxes and the
  biosphere. In: Rabbinge, R. et al. (Eds), Theoretical Production
  Ecology: Reflections and Prospects.
- Gustavsson, A.-M., Angus, J.F. & Torsell, B.W.R. (1995). An
  integrated model for growth and nutritional value of
  timothy. Agricultural Systems 47: 73-92.
- Van Oijen M, Höglind M, Cameron DR, Thorsen SM
  (2015). BASGRA_2014. http://dx.doi.org/10.5281/zenodo.27867
- Van Oijen M, Rougier J, Smith R (2005). Bayesian calibration of
  process-based forest models: bridging the gap between models and
  data. Tree Physiology 25: 915-927.
* APPENDIX A: Details of file changes
- In this appendix we examine more closely how files are changed in
  BASGRA_N compared to BASGRA_2014
** File changes in the top directory
- The file BASGRA.DLL is changed because the new FORTRAN code required
  re-compilation of the model.
** File changes in subdirectory 'BC'
- This subdirectory contains files that are used to run Bayesian
  Calibration (BC) of the model and analyse the results.
*** Changes in BC-files that include a call to 'run_model'
- Files that run the model - through a call to the R-function
  'run_model' - are changed. This is because running BASGRA_N requires
  specifying levels of N-fertilisation and N-deposition. So there are
  small changes in: 'BC_BASGRA_MCMC.R',
  'BC_BASGRA_MCMC_init_general.R', and 'BC_plot_outputs_data.R'.
*** Changes in specification of sites
- It is now possible to include all sites (both for calibration and
  testing) in the calibration set-up, no need to leave the sites out
  whose data are not used for calibration. We can now list all the
  sites in the BC-initialisation file 'BC_BASGRA_MCMC_init_[].R', but
  we need to specify which of the sites are going to be used in the
  BC, and which sites are only there for testing and plotting. The
  idea is to make it a lot easier and quicker to check how model
  calibration affects BASGRA results for test-sites. In the titles of
  the plots of output vs. data is stated whether a site was a
  'CALIBRATION site' or a 'TEST site'.
- To implement this, changes were made in the definitions of
  'calc_logL_s' and 'plot_outputs_data_s' in file
  BC_BASGRA_MCMC_init_general.R.
*** Changes in specification of measured variables
- Another change is in the specification of the variables whose
  measurements are used in the calibration. We now no longer need the
  names of calibration variables in data sets to be identical to
  BASGRA variable names. If the name of a variable in the data differs
  from the one used in BASGRA for the same quantity, then we can
  specify that correspondence in file 'BC_BASGRA_MCMC_init_general.R'.
*** Changes in files for plotting BC-results
- When many parameters are calibrated (as in the cv-specific BCs
  with all many parameters), multiple pages are needed to plot results
  for each parameter. We have now set a maximum of 8 rows and 10 columns
  per page in the traceplots and prior/posterior histograms.
- We also added new files for plotting BC-results. Three more plots
  can now easily be made after a BC:
  - Boxplots for all BC-parameters: see
    'BC\BC_plot_parameters_boxplots.R'.
  - Plots of total yield (YIELD_TOT) and maximum dry matter (DM_MAX)
    against cumulative fertilisation (Nfert_TOT): see
    'BC\BC_plot_YIELD_TOT&DM_MAX_vs_Nfert_TOT.R'.
  - Plots of selected output variables over time for the prior mode,
    maximum likelihood and MAP parameter vectors: see function 'BC_plot_outputs()'
    defined in the file 'BC\BC_plot_outputs.R'.
*** Changes in calculation of the likelihood
- The quantification of data uncertainty (needed for the likelihood
  function) has changed. In common practice, there are two extreme
  methods for data uncertainty that we do not want to follow. The two
  extreme methods are:
  - Assuming that data uncertainty depends on the type of variable
    (DM, LAI, TILTOT etc.) but not on the value of the variable. So
    tiny values are assumed to come with the same uncertainty
    (expressed as the data standard deviation SD) as very large values.
  - Assuming that data uncertainty is proportional to the data value,
    i.e. have a constant coefficient of variation. In this approach
    the SD for small data values becomes very small, making those
    data points extremely influential in the BC.
- Our method lies in between the two extreme methods. Let y be a data
  value, and let y_max be the highest value for that variable in our whole
  data set. We specify a coefficient of variation SD_ymax that is
  appropriate for y_max. So SD_ymax = CV_ymax * y_max. With those
  definitions our intermediate method of data uncertainty
  quantification is:
  - SD_y = CV_ymax * sqrt( y_max * y )
- That is equivalent to:
  - SD_y = SD_ymax * sqrt( y / y_max ).
- This method assigns the highest data uncertainty (SD) to the highest
  values of y but the SD decreases less than proportionately for
  smaller y. Instead of scaling linearly with the data value y, the SD
  now scales with the square root of y.
- We specify (as before) the CV-values in the initialisation file for
  the BC, which is typically called something like 'BC_BASGRA_MCMC_init...'.
 
** File changes in subdirectory 'initialisation'
*** File 'initialise_BASGRA_general.R'
- Declaration of the calendars for N-fertilisation and N-deposition.
- Change in definition of function 'run_model', again to accommodate
  fertilisation and deposition.
- The vectors "outputNames" and "outputUnits" have been extended
  with 29 additional output variables, bringing the total (NOUT)
  to 68.
- The sensitivity analysis function, 'SA()', was changed slightly to
  allow for different types of plots, to be specified using the new
  function argument 'type_plot'. The default is still "pdf" but
  "png" and "jpg" can also be chosen.
- A minor bug in function 'plot_outputs_Setups' was corrected.
*** Site-specific initialisation files
- In the initialisation-files for specific sites,
  e.g. 'initialise_BASGRA_Saerheim_0102_early_Gri.R', the
  N-fertilisation and N-deposition calendars for the site are now
  specified.
** File changes in subdirectory 'model' (the FORTRAN files)
*** File 'BASGRA.f90'
- The header of subroutine 'BASGRA' now includes 'CALENDAR_FERT' and
  'CALENDAR_NDEP'. The calendar values are stored in arrays named
  'DAYS_FERT', 'DAYS_NDEP', 'NFERTV' and 'NDEPV'.
- The parameter array is declared as an array of 120 reals.  The
  number 120 is an upper bound, the actual number of parameters
  is less than that.
- Additional state variables are declared and their initial values
  set.
- Additional intermediate and rate variables are declared.
- Five new subroutines are called: 'N_fert', 'N_dep', 'CNsoil',
  'Nplant' and 'Digestibility'.
- The call to subroutine 'Growth' now has three extra inputs and one
  extra output.
- The call to subroutine 'FRDRUNIR' is simplified (variables DRAIN
  and RUNOFF no longer passed through the header).
- There are many additional output variables.
- There are 8 additional state equations for the new state
  variables (one plant variable, NSH, and seven soil variables:
  CLITT, CSOMF, CSOMS, NLITT, NSOMF, NSOMS, NMIN).
- There are calculations that resemble state equations (but are in
  fact transformations) for deriving total fertilisation (Nfert_TOT)
  and maximum aboveground dry matter (DM_MAX).
- There are additional calculations for a range of different output
  variables relevant to dry matter distribution, protein content, ash
  content, cell-wall content and digestibility.
*** File 'environment.f90'
- This file is not changed.
*** Parameterisation files
- The file 'set_params.f90' now sets the values for an array of 107
  parameters (previously it was 81). The extra parameters are declared
  in the files 'parameters_plant.f90' and 'parameters_site.f90'.
*** File 'plant.f90'
- This file has been changed much to include N-processes in plants.
- New variables are being declared.
- Alterations to subroutine 'growth':
  - Subroutine 'growth' has three additional inputs (LAI,NSH,NMIN) and
    one additional output (NSHmob).
  - The first part of the subroutine, up to and including the first
    estimates for the "sinks" GLAISI, GLVSI and GSTSI, is
    unaltered. But then nitrogen-processes are invoked to possibly
    reduce those sink strengths.
  - First, there is a calculation of how much excess N there is in the
    shoot, i.e. the difference between the amount of N in the shoot
    (NSH) and the amount expected if N would follow the same
    decreasing profile as light. If the excess is positive, it is
    remobilised at a constant relative rate (time constant parameter
    TCNSHMOB). The amount of N thus becoming available for growth from
    within the plants is called 'NSHmob'. Total N available for
    growth, 'NSOURCE' is then calculated as NSHmob plus a constant
    fraction of soil mineral N (NMIN divided by time constant
    TCNUPT).
  - The 'shoot sink strength for N', NSINK is calculated as the sum of
    the first estimates of GLVSI and GSTSI, times the constant maximum
    NC-ratio of shoot tissue (parameter NCSHMAX).
  - Then the growth realisation factor fNgrowth is defined as
    NSOURCE/NSINK, but not exceeding 1. Finally, the shoot sink
    strengths are revised by multiplying them with
    fNgrowth. Allocation then proceeds as before.
- Alterations to subroutine 'Foliage2':
  - Subroutine 'Foliage2' has a few cosmetic changes (e.g. renaming
    intermediate variable for potential site filling, TV2, to the
    clearer name FSPOT) and one major change: the rate of leaf
    appearance RLEAF is now proportional to the N-growth realisation
    factor fNgrowth. 
- New subroutine 'Nplant'
  - The new subroutine Nplant is used to calculate N-fluxes within the
    plants and between plants and environment.
  - First, three intermediate variables are calculated: (1) the
    normalised amount of N in the shoots (NSHNOR, i.e. the amount of N
    in shoots divided by the maximum allowable N defined as shoot C
    multiplied with the maximum shoot N-C ratio NCSHMAX), (2) the
    maximum allowable value of the nitrogen extinction coefficient in
    the vertical sward profile (KNMAX), and (3) the actual value of
    the nitrogen extinction coefficient (KN). The latter is only
    approximative, based on application of Taylor-series expansion.
  - Then a N-C realisation factor, fNCgrowth, is calculated as a
    linear function of fNgrowth. The N-C realisation factor is used to
    reduce the N content of new shoot growth in case of limiting
    N-availability.
  - Then the three processes of changes in shoot N due to growth,
    senescence and harvesting are calculated, using assumptions about
    the exponential profile.
  - That is followed by calculation of the rates of change in root N
    due to growth and senescence, assuming a constant N-C ratio in
    roots.
  - Finally, three fluxes are calculated which are the direct
    consequence of the fluxes calculated above, i.e. they require no
    additional assumptions or mechanisms. These are: (1) GNmob, the
    flux from shoot N-remobilisation to new plant growth, (2)
    NSHmobsoil, the flux from shoot N-remobilisation to soil in case
    the NSINK is too small to use up all remobilised nitrogen, (3)
    Nupt, the rate of N-uptake from the soil.
- New subroutine 'Digestibility'.
  - This subroutine calculates cell-wall contents and digestibilities
    as a function of phenological stage and aboveground dry matter
    distribution.
  - Cell-wall fractions in leaves (F_WALL_LV) and stems (F_WALL_ST)
    increase linearly with phenological stage.
  - The cell-wall fraction of the whole shoot (=leaves + stems +
    reserves) is the weighted average of the cell-wall contents of
    the three components (assumed zero for reserves).
  - The cell-wall fraction of total aboveground dry matter (=shoot +
    stubble) is the weighted average of the cell-wall contents of
    its components (assumed 100% for stubble).
  - Cell-wall digestibility decreases linearly with phenological
    stage.
  - Digestibility of leaves, stems, shoot and aboveground dry matter
    are calculated from their cell-wall content and its digestibility.
*** File 'resources.f90'
- One new soil variable is calculated, the water-filled pore space
  (WFPS).
*** File 'soil.f90'
- This file is one of the three BASGRA FORTRAN-files that has changed
  the most (together with BASGRA.f90 and plant.f90) to represent C- and
  N-processes.
- A large number of new variables are declared.
- Altered subroutine 'FRDRUNIR'.
  - This subroutine received one minor change in that DRAIN and RUNOFF
    are no longer passed through the header of the subroutine but via
    the list of module-variables at the top of 'soil.f90'.
- New subroutines:
  - The new subroutine 'N_fert' checks for each simulation day whether
    there is a fertilisation event specified in the calendar, and of
    what magnitude.
  - The new subroutine 'N_dep' calculates the N-deposition rate at
    each simulated day, by linearly interpolating between the values
    provided in the deposition-calendar.
  - The subroutine 'CNsoil' is also new for BASGRA, but it is almost
    identical to code for forest model BASFOR. This subroutine
    calculates the transformations of litter and organic matter pools
    for both C and N, and how much CO2 and mineral N are produced as
    side- or end-products. The subroutine also calculates N-fixation,
    N-leaching and N-emission to N2O and NO.
** File changes in subdirectory 'parameters'
- 32 lines were added at the end of 'parameters.txt', one for each new
  parameter.
** File changes in subdirectory 'data'
- We now have data files that include information on variables for
  nitrogen content, ash-content, cell-wall (fibre) content and
  digestibility.

* APPENDIX B: New variables
** Introduction
In this appendix we list all variables that were added when moving from
BASGRA to BASGRA_N. We give their names and units. Areas (m2) are
always ground area unless otherwise indicated. We distinguish the
following types of variables:
1. State variables
2. Non-state variables
   - Input variable: Variables whose values are not calculated by the
     model but defined in the initialization file or imported from an
     external data file.
   - Intermediate variables: Variables that express intermediate results
     in the calculation of rate or output variables.
   - Output variables: Variables whose calculation can be deleted without
       affecting any of the other model results.
     - Output variables whose identifier is given in quotation marks ("")
       do not have explicit names in BASGRA.f90, but names are given to
       them in the plotting routines.
   - Rate variables: Variables that directly change state
     variables. They are part of the state update equation and their
     unit includes "d-1".
-  SOC = Soil Organic Carbon, SOM = Soil Organic Matter, SON = Soil
   Organic Nitrogen.
** New state variables (BASGRA.f90)
|----------------+---------+----------------------------------|
| State variable | Unit    | Meaning                          |
|----------------+---------+----------------------------------|
| CLITT          | g C m-2 | Carbon in litter                 |
| CSOMF          | g C m-2 | Carbon in fast-decomposing SOM   |
| CSOMS          | g C m-2 | Carbon in slow-decomposing SOM   |
| NLITT          | g N m-2 | Nitrogen in litter               |
| NSOMF          | g N m-2 | Nitrogen in fast-decomposing SOM |
| NMIN           | g N m-2 | Mineral nitrogen                 |
| NSOMS          | g N m-2 | Nitrogen in slow-decomposing SOM |
| NSH            | g N m-2 | Nitrogen in shoot                |
|----------------+---------+----------------------------------|
** New non-state variables (BASGRA.f90)
|-----------------+---------------+------------------------------------------------------+--------------|
| Variable        | Unit          | Meaning                                              | Type         |
|-----------------+---------------+------------------------------------------------------+--------------|
| dCLITT          | g C m-2 d-1   | Loss of litter C in decomposition                    | Rate         |
| dCLITTsomf      | g C m-2 d-1   | Conversion of litter-C to fast SOC                   | Rate         |
| dCSOMF          | g C m-2 d-1   | Loss of fast organic C in decomposition              | Rate         |
| dCSOMFsoms      | g C m-2 d-1   | Conversion of fast to slow SOC                       | Rate         |
| dCSOMS          | g C m-2 d-1   | Loss of fast organic C in decomposition              | Rate         |
| DM              | g DM m-2      | Dry matter aboveground                               | Intermediate |
| DMLV            | g DM m-2      | Dry matter leaves                                    | Intermediate |
| DMRES           | g DM m-2      | Dry matter reserves                                  | Intermediate |
| DMSH            | g DM m-2      | Dry matter shoot                                     | Intermediate |
| DMST            | g DM m-2      | Dry matter stems                                     | Intermediate |
| DMSTUB          | g DM m-2      | Dry matter stubble                                   | Intermediate |
| DM_MAX          | g DM m-2      | Maximum aboveground dry matter since start of run    | Output       |
| dNLITT          | g N m-2 d-1   | Loss of litter N in decomposition                    | Rate         |
| DNRT            | g N m-2 d-1   | Loss of root N in senescence                         | Rate         |
| DNSH            | g N m-2 d-1   | Loss of shoot N in senescence                        | Rate         |
| dNSOMF          | g N m-2 d-1   | Loss of fast SON in decomposition                    | Rate         |
| dNSOMS          | g N m-2 d-1   | Loss of slow SON in decomposition                    | Rate         |
| F_ASH           | g m-2         | Ash content of shoot dry matter                      | Output       |
| F_DIGEST_DM     | -             | Digestibility of aboveground dry matter              | Output       |
| F_DIGEST_DMSH   | -             | Digestibility of shoot dry matter                    | Output       |
| F_DIGEST_LV     | -             | Digestibility of leaf dry matter                     | Output       |
| F_DIGEST_ST     | -             | Digestibility of stem dry matter                     | Output       |
| F_DIGEST_WALL   | -             | Digestibility of cell walls                          | Output       |
| F_PROTEIN       | g g-1 DM      | Crude protein content of shoot dry matter            | Output       |
| F_WALL_DM       | g wall g-1 DM | Fraction of aboveground dry matter that is cell wall | Output       |
| F_WALL_DMSH     | g wall g-1 DM | Fraction of shoot dry matter that is cell wall       | Output       |
| F_WALL_LV       | g wall g-1 DM | Fraction of leaf dry matter that is cell wall        | Output       |
| F_WALL_ST       | g wall g-1 DM | Fraction of stem dry matter that is cell wall        | Output       |
| GNRT            | g N m-2 d-1   | Growth of root N                                     | Intermediate |
| GNSH            | g N m-2 d-1   | Growth of shoot N                                    | Rate         |
| HARVNSH         | g N m-2 d-1   | Harvesting of shoot N                                | Rate         |
| NCDSH           | g N g-1 C     | N-C ratio of shoot senescence                        | Intermediate |
| NCGSH           | g N g-1 C     | N-C ratio of shoot growth                            | Intermediate |
| NCHARVSH        | g N g-1 C     | N-C ratio of harvested material                      | Intermediate |
| Ndep            | g N m-2 d-1   | Atmospheric N deposition                             | Rate         |
| Nemission       | g N m-2 d-1   | N emission (NO plus N2O)                             | Rate         |
| NemissionN2O    | g N m-2 d-1   | Emission of nitrous oxide                            | Output       |
| NemissionNO     | g N m-2 d-1   | Emission of nitric oxide                             | Output       |
| Nfert           | g N m-2 d-1   | N fertilisation                                      | Rate         |
| Nfert_TOT       | g N m-2       | Cumulative N-fertilisation from start of run         | Output       |
| Nfixation       | g N m-2 d-1   | N fixation                                           | Rate         |
| Nleaching       | g N m-2 d-1   | N leaching                                           | Rate         |
| NLITTsomf       | g N m-2 d-1   | Conversion of litter N to fast SON                   | Rate         |
| Nmineralisation | g N m-2 d-1   | N mineralisation                                     | Rate         |
| NSHmob          | g N m-2 d-1   | Shoot N                                              | Rate         |
| NSHmobsoil      | g N m-2 d-1   | Remobilised shoot N lost to the soil                 | Rate         |
| NSOMFsoms       | g N m-2 d-1   | Conversion of fast to slow SON                       | Rate         |
| Nupt            | g N m-2 d-1   | N uptake                                             | Rate         |
| rCLITT          | g C m-2 d-1   | Loss of litter C in run-off                          | Rate         |
| rCSOMF          | g C m-2 d-1   | Loss of fast SOC in run-off                          | Rate         |
| rNSOMF          | g N m-2 d-1   | Loss of fast SON in run-off                          | Rate         |
| rNLITT          | g N m-2 d-1   | Loss of litter N in run-off                          | Rate         |
| Rsoil           | g C m-2 d-1   | Soil respiration                                     | Output       |
| YIELD           | g DM m-2 d-1  | Daily yield                                          | Output       |
| YIELD_LAST      | g DM m-2 d-1  | Most recent yield                                    | Output       |
| YIELD_TOT       | g DM m-2      | Cumulative yield                                     | Output       |
|-----------------+---------------+------------------------------------------------------+--------------|

** New variables (soil.f90)
|-----------------+-------------+------------------------------------------+--------------|
| Variable        | Unit        | Meaning                                  | Type         |
|-----------------+-------------+------------------------------------------+--------------|
| dCLITT          | g C m-2 d-1 | Loss of litter C in decomposition        | Rate         |
| dCLITTrsoil     | g C m-2 d-1 | Loss of litter C to CO2 in decomposition | Intermediate |
| dCLITTsomf      | g C m-2 d-1 | Conversion of litter-C to fast SOC       | Rate         |
| dCSOMF          | g C m-2 d-1 | Loss of fast SOC in decomposition        | Rate         |
| dCSOMFrsoil     | g C m-2 d-1 | Loss of fast SOC to CO2 in decomposition | Intermediate |
| dCSOMFsoms      | g C m-2 d-1 | Conversion of fast to slow SOC           | Rate         |
| dCSOMS          | g C m-2 d-1 | Loss of fast SOC in decomposition        | Rate         |
| dNLITT          | g N m-2 d-1 | Loss of litter N in decomposition        | Rate         |
| dNSOMF          | g N m-2 d-1 | Loss of fast SON in decomposition        | Rate         |
| dNSOMS          | g N m-2 d-1 | Loss of slow SON in decomposition        | Rate         |
| fN2O            | g N g-1 N   | Fraction of N emission that is as N2O    | Intermediate |
| fTsoil          | -           | Temperature effect on decomposition      | Intermediate |
| Ndep            | g N m-2 d-1 | Atmospheric N deposition                 | Rate         |
| Nemission       | g N m-2 d-1 | N emission (NO plus N2O)                 | Rate         |
| NemissionNO     | g N m-2 d-1 | Emission of nitric oxide                 | Output       |
| NemissionN2O    | g N m-2 d-1 | Emission of nitrous oxide                | Output       |
| Nfert           | g N m-2 d-1 | N fertilisation                          | Rate         |
| Nfixation       | g N m-2 d-1 | N fixation                               | Rate         |
| Nleaching       | g N m-2 d-1 | N leaching                               | Rate         |
| NLITTnmin       | g N m-2 d-1 | Loss of litter N to mineral N            | Intermediate |
| NLITTsomf       | g N m-2 d-1 | Conversion of litter N to fast SON       | Rate         |
| Nmineralisation | g N m-2 d-1 | N mineralisation                         | Rate         |
| NSOMFnmin       | g N m-2 d-1 | Loss of fast SON to mineral N            | Intermediate |
| NSOMFsoms       | g N m-2 d-1 | Conversion of fast to slow SON           | Rate         |
| rCLITT          | g C m-2 d-1 | Loss of litter C in run-off              | Rate         |
| rCSOMF          | g C m-2 d-1 | Loss of fast SOC in run-off              | Rate         |
| rNLITT          | g N m-2 d-1 | Loss of litter N in run-off              | Rate         |
| rNSOMF          | g N m-2 d-1 | Loss of fast SON in run-off              | Rate         |
| Rsoil           | g C m-2 d-1 | Soil respiration                         | Output       |
|-----------------+-------------+------------------------------------------+--------------|

** New variables (plant.f90)
|-------------------+---------------+-------------------------------------------------------+--------------|
| Variable          | Unit          | Meaning                                               | Type         |
|-------------------+---------------+-------------------------------------------------------+--------------|
| DM                | g DM m-2      | Dry matter aboveground                                | Intermediate |
| DMLV              | g DM m-2      | Dry matter leaves                                     | Intermediate |
| DMRES             | g DM m-2      | Dry matter reserves                                   | Intermediate |
| DMSH              | g DM m-2      | Dry matter shoot                                      | Intermediate |
| DMST              | g DM m-2      | Dry matter stems                                      | Intermediate |
| DMSTUB            | g DM m-2      | Dry matter stubble                                    | Intermediate |
| DNRT              | g N m-2 d-1   | Loss of root N in senescence                          | Rate         |
| DNSH              | g N m-2 d-1   | Loss of shoot N in senescence                         | Rate         |
| fNCgrowth         | -             | Effect of N-limitation on N-C ratio of growing tissue | Intermediate |
| fNgrowth          | -             | Nitrogen source-sink ratio                            | Intermediate |
| F_DIGEST_DM       | -             | Digestibility of aboveground dry matter               | Output       |
| F_DIGEST_DMSH     | -             | Digestibility of shoot dry matter                     | Output       |
| F_DIGEST_LV       | -             | Digestibility of leaf dry matter                      | Output       |
| F_DIGEST_ST       | -             | Digestibility of stem dry matter                      | Output       |
| F_DIGEST_WALL     | -             | Digestibility of cell walls                           | Output       |
| F_DIGEST_WALL_MIN | -             | Minimum digestibility of cell walls                   | Intermediate |
| F_WALL_DM         | g wall g-1 DM | Fraction of aboveground dry matter that is cell wall  | Output       |
| F_WALL_DMSH       | g wall g-1 DM | Fraction of shoot dry matter that is cell wall        | Output       |
| F_WALL_LV         | g wall g-1 DM | Fraction of leaf dry matter that is cell wall         | Output       |
| F_WALL_LV_MIN     | -             | Minimum fraction of leaf dry matter that is cell wall | Intermediate |
| F_WALL_ST         | g wall g-1 DM | Fraction of stem dry matter that is cell wall         | Output       |
| F_WALL_ST_MIN     | -             | Minimum fraction of stem dry matter that is cell wall | Intermediate |
| GNmob             | g N m-2 d-1   | Contribution of mobilised N to growth                 | Intermediate |
| GNRT              | g N m-2 d-1   | Growth of root N                                      | Intermediate |
| GNSH              | g N m-2 d-1   | Growth of shoot N                                     | Rate         |
| HARVNSH           | g N m-2 d-1   | Harvesting of shoot N                                 | Rate         |
| KN                | m2 m-2 leaf   | Nitrogen extinction coefficient                       | Intermediate |
| KNMAX             | m2 m-2 leaf   | Maximum value of nitrogen extinction coefficient      | Intermediate |
| NCDSH             | g N g-1 C     | N-C ratio of shoot senescence                         | Intermediate |
| NCGSH             | g N g-1 C     | N-C ratio of shoot growth                             | Intermediate |
| NCHARVSH          | g N g-1 C     | N-C ratio of harvested material                       | Intermediate |
| NSH               | g N m-2       | Nitrogen in shoot                                     | State        |
| NSHK              | g N m-2       | Nitrogen in shoot if N-profile equals light-profile   | Intermediate |
| NSHmob            | g N m-2 d-1   | Shoot N                                               | Rate         |
| NSHmobsoil        | g N m-2 d-1   | Remobilised shoot N lost to the soil                  | Rate         |
| NSHNOR            | -             | Normalised shoot nitrogen content                     | Intermediate |
| Nupt              | g N m-2 d-1   | N uptake                                              | Rate         |
|-------------------+---------------+-------------------------------------------------------+--------------|
* APPENDIX C: New parameters
** Introductory comments
In this appendix we list all parameters that were added when moving from
BASGRA to BASGRA_N. We give their names and units. Areas (m2) are
always ground area unless otherwise indicated. SOC = Soil Organic
Carbon, SOM = Soil Organic Matter.
** New parameters in BASGRA.f90
|-----------+-----------+--------------------------------------+----------------------+------------------|
| Parameter | Unit      | Meaning                              | Declared where       | Quantified where |
|-----------+-----------+--------------------------------------+----------------------+------------------|
| CLITT0    | g C m-2   | Initial value of CLITT               | parameters_site.f90  | parameters.txt   |
| CNLITT0   | g C g-1 N | Initial C-N ratio of litter          | parameters_site.f90  | parameters.txt   |
| CNSOMF0   | g C g-1 N | Initial C-N ratio of fast SOM        | parameters_site.f90  | parameters.txt   |
| CNSOMS0   | g C g-1 N | Initial C-N ratio of slow SOM        | parameters_site.f90  | parameters.txt   |
| CSOM0     | g C m-2   | Initial value of                     | parameters_site.f90  | parameters.txt   |
| FCSOMF0   | g C g-1 C | Initial fraction of SOC that is fast | parameters_site.f90  | parameters.txt   |
| NCSHMAX   | g N g-1 C | Maximum N-C ratio of shoot           | parameters_plant.f90 | parameters.txt   |
| NMIN0     | g N m-2   | Initial value of soil mineral N      | parameters_site.f90  | parameters.txt   |
|-----------+-----------+--------------------------------------+----------------------+------------------|
** New parameters in soil.f90
|-----------+---------------+---------------------------------------------------------+---------------------+---------------------|
| Parameter | Unit          | Meaning                                                 | Declared where      | Quantified where    |
|-----------+---------------+---------------------------------------------------------+---------------------+---------------------|
| FLITTSOMF | g g-1         | Fraction of decomposed litter becoming fast SOM         | parameters_site.f90 | parameters.txt      |
| FSOMFSOMS | g g-1         | Fraction of decomposed fast SOM                         | parameters_site.f90 | parameters.txt      |
| KNEMIT    | g N g-1 N d-1 | Fraction of mineral N emitted in wet soil               | parameters_site.f90 | parameters.txt      |
| KNFIX     | g N g-1 C     | Nitrogen fixation per unit of root growth               | parameters_site.f90 | parameters_site.f90 |
| RFN2O     | -             | Sensitivity of N-emission partitioning to soil wetness  | parameters_site.f90 | parameters.txt      |
| RNLEACH   | g N g-1 N     | Relative concentration of mineral N in leaching water   | parameters_site.f90 | parameters.txt      |
| RRUNBULK  | g g-1         | Relative concentration of soil in run-off water         | parameters_site.f90 | parameters_site.f90 |
| TCLITT    | d             | Time constant of litter decomposition at 10 deg C       | parameters_site.f90 | parameters.txt      |
| TCSOMF    | d             | Time constant of fast SOM decomposition at 10 deg C     | parameters_site.f90 | parameters.txt      |
| TCSOMS    | d             | Time constant of slow SOM decomposition at 10 deg C     | parameters_site.f90 | parameters.txt      |
| TMAXF     | degC          | Temperature at which decomposition is maximal           | parameters_site.f90 | parameters.txt      |
| TSIGMAF   | degC          | Resilience of decomposition to temperature change       | parameters_site.f90 | parameters.txt      |
| WFPS50N2O | -             | Water filled pore space at which N-emission is half N2O | parameters_site.f90 | parameters.txt      |
|-----------+---------------+---------------------------------------------------------+---------------------+---------------------|

** New parameters in plant.f90
|-----------+-----------+----------------------------------------------+----------------------+------------------|
| Parameter | Unit      | Meaning                                      | Declared where       | Quantified where |
|-----------+-----------+----------------------------------------------+----------------------+------------------|
| FNCGSHMIN | -         | Relative minimum N-C ratio of growing tissue | parameters_plant.f90 | parameters.txt   |
| NCR       | g N g-1 C | N-C ratio of roots                           | parameters_plant.f90 | parameters.txt   |
| NCSHMAX   | g N g-1 C | Maximum N-C ratio of shoot                   | parameters_plant.f90 | parameters.txt   |
| TCNSHMOB  | d         | Time constant of shoot N remobilisation      | parameters_plant.f90 | parameters.txt   |
| TCNUPT    | d         | Time constant of soil mineral N uptake       | parameters_plant.f90 | parameters.txt   |
|-----------+-----------+----------------------------------------------+----------------------+------------------|

* APPENDIX D: New constants
** Introductory comments
In this appendix we list all constants that were added when moving from
BASGRA to BASGRA_N. We give their names and units. Areas (m2) are
always ground area unless otherwise indicated. 
** New constants in BASGRA.f90
|----------+-------+---------------+--------------------------------------+----------------------+----------------------|
| Constant | Value | Unit          | Meaning                              | Declared where       | Quantified where     |
|----------+-------+---------------+--------------------------------------+----------------------+----------------------|
|          |       |               |                                      |                      |                      |
| YIELDI   |    0. | g DM m-2 d-1  | Initial value of yield               | parameters_plant.f90 | parameters_plant.f90 |
|          |  6.25 | g g-1 N       | Protein per unit N                   | -                    | BASGRA.f90           |
|          | 0.069 | g g-1 DM      | Ash content at zero protein content  | -                    | BASGRA.f90           |
|          |  0.14 | g g-1 protein | Additional ash content per g protein | -                    | BASGRA.f90           |
|----------+-------+---------------+--------------------------------------+----------------------+----------------------|
** New constants in soil.f90
|----------+-------+--------+-----------------------------------------------------+----------------+------------------|
| Constant | Value | Unit   | Meaning                                             | Declared where | Quantified where |
|----------+-------+--------+-----------------------------------------------------+----------------+------------------|
|          | 0.001 | m mm-1 | Unit conversion                                     | -              | soil.f90         |
|          |    2. | degC-1 | Constant in temperature effect on SOM decomposition | -              | soil.f90         |
|          |   10. | degC   | Constant in temperature effect on SOM decomposition | -              | soil.f90         |
|----------+-------+--------+-----------------------------------------------------+----------------+------------------|

** New constants in plant.f90
|----------+-------+------+-----------------------------------------------------+----------------+------------------|
| Constant | Value | Unit | Meaning                                             | Declared where | Quantified where |
|----------+-------+------+-----------------------------------------------------+----------------+------------------|
|          |  0.25 | -    | Constant in calculation of N extinction coefficient | -              | plant.f90        |
|          |   5/8 | -    | Constant in calculation of N extinction coefficient | -              | plant.f90        |
|          |   2/3 | -    | Constant in calculation of N extinction coefficient | -              | plant.f90        |
|          |   1.5 | -    | Constant in calculation of N extinction coefficient | -              | plant.f90        |
|          |     3 | -    | Constant in calculation of N extinction coefficient | -              | plant.f90        |
|----------+-------+------+-----------------------------------------------------+----------------+------------------|

